---
title: "Open!Make: Towards open and FAIR hardware"
subtitle: "24 months project starting in 04/2021"
06/2021author:
  - name: Prof. Dr.-Ing. Roland Jochem
    email: roland.jochem@tu-berlin.de
    address1: Chair of Quality Science, Institute for Machine Tools
    address2: and Factory Management, Technische Universität Berlin (TUB)
    phone: +49 30 314 22005.
  - name: Prof. Matthew Larkum
    email: matthew.larkum@hu-berlin.de
    address2: Institute of Biology, Humboldt-Universität zu Berlin (HUB).
    phone: +49 30 450 539 152.
  - name: Prof. Tim Landgraf
    email: tim.landgraf@fu-berlin.de
    address1: Dahlem Center for Machine Learning and Robotics,
    address2:  Institute of Computer Science, Freie Universität Berlin (FUB)
    phone: +49 30 838 75114.
    
papersize: a4
linestretch: 1.2
fontsize: 12pt
links-as-notes: true
output:
  pdf_document:
    template: ../my-template.tex
    latex_engine: xelatex
    keep_tex: true
mainfont: Times New Roman  
---

# Out and Incoming Fellowship Program

# 1. Incoming Fellowship 1- Guidance for researchers

The open.make project would like to give Dr. Julieta Arancio the opportunity to work inside the open.make project for three months. She will be mentoring the creation of "guidelines on the documentation, evaluation and publishing of open, FAIR hardware" (task T3.1 of the open.make application).
In addition, Dr Arancio will lead the preparation and implementation of a workshop for BUA researchers, where open source hardware principles and practives will be taught.
Dr Arancio is one maintainer of the open hardware makers program, a mentorship program aiming at training researchers in the design of open source hardware projects. She is therefore an expert in this domain.
She is presently working as a post doc at the Drexel University and University of Bath.

Dr Arancio has been in contact with the open.make team since the grant application process, where her expertise helped designing the scope of this project. We expect to continue our collaboration beyond this project, with the possiblities to develop closer collaborations.

The work of Dr. Arancio will make a huge difference in the quality and reach of the guidance document, as she brings years of experience in open source hardware project design, documentation and publication, as well as a large international network of open source hardware enthusiasts.

\newpage

<!--
- an einem für das Objective relevanten Thema zu forschen
- Jenseits des Aufenthalts an einer der BUA Einrichtungen sollen die Fellows längerfristig Teil des Netzwerkes des Objective werden

content: 
- Mentorenrolle für ein Thema bzw. ein konkretes Projekt des Objective übernimmt
- nach dem initialen Gastaufenthalt regelmäßig im Austausch / Kontakt mit dem das Projekt bearbeitenden Team bleibt (Zusammenarbeit und den Austausch auch nachhaltig sicher zu stellen)
- führt in Absprache mit der gastgebenden Einrichtung Veranstaltungen durch
- Die gastgebende Einrichtung ergibt sich in Abhängigkeit vom Thema und der organisationalen Verankerung der das Thema bearbeitenden Arbeitsgruppe.
-->
# 2. Incoming grant 2- Standardisation in hardware documentation

# 3. Outgoing grant -  Open hardware and the TU Delft open science strategy

- mit an anderen Einrichtungen etablierten Strukturen oder Prozessen vertraut zu machen
- aktuell an der Entwicklung und insbesondere Implementierung von Prozessen und / oder Strukturen arbeiten
content:
- Gegenstand und Ziel des Aufenthalts erläutert werden
- kurze Beschreibung der Gastinstitution
-  Auswahl der Institution begründen
-  Aufnahmeerklärung der gewählten Gasteinrichtung einschließlich der Zusage, dass ein Arbeitsplatz gestellt und der Zugang zu erforderlichen Ressourcen bzw. erforderlicher Infrastruktur gewährt wird
-  Übersicht der beantragten Mittel